name: cached_streamable
description: A dead-simple interface for creating a streamable data source.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.8.0

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^3.0.1
