name: cached_streamable
description: Simple interface for creating a streamable data source that caches it latest value.
version: 1.1.0
homepage: https://github.com/Luckey-Elijah/cached_streamable
repository: https://github.com/Luckey-Elijah/cached_streamable
issue_tracker: https://github.com/Luckey-Elijah/cached_streamable/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^3.0.1
