name: cached_streamable

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "lib/**"
      - "test/**"
      - "analysis_options.yaml"
      - "pubspec.yaml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "lib/**"
      - "test/**"
      - "analysis_options.yaml"
      - "pubspec.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1